name: Autograding Tests
on:
  - push
  - workflow_dispatch
  - repository_dispatch
permissions:
  checks: write
  actions: read
  contents: read
jobs:
  run-autograding-tests:
    runs-on: ubuntu-latest
    if: github.actor != 'github-classroom[bot]'
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.19.3'
      - run: flutter pub get
      - name: Dart analyze
        id: dart-analyze
        run: dart analyze
      - name: Flutter tests
        id: flutter-tests
        run: flutter test
      - name: Autograding Reporter
        uses: ./
        env:
          DART-ANALYZE_RESULTS: ""${{steps.dart-analyze.outputs.result}}""
          FLUTTER-TESTS_RESULTS: ""${{steps.flutter-tests.outputs.result}}""
        with:
          runners: dart-analyze,flutter-tests